name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Determine changed files
        id: changes
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      - name: Instal and Build landing
        if: contains(env.CHANGED_FILES, 'landing/')
        run: |
          npm install
          npm run build
        working-directory: ./landing

      - name: Deploy landing via FTP
        if: contains(env.CHANGED_FILES, 'landing/')
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./landing/dist/
          server-dir: /

      - name: Instal and Build dashboard
        if: contains(env.CHANGED_FILES, 'dashboard/')
        run: |
          npm install
          npm run build
        working-directory: ./dashboard

      - name: Deploy dashboard via FTP
        if: contains(env.CHANGED_FILES, 'dashboard/')
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dashboard/dist/
          server-dir: /dashboard/
