name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [landing, dashboard]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Determine changed paths
      #   id: determine_changes
      #   run: |
      #     echo "changed_paths=$(git diff --name-only ${{ github.sha }})" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and build ${{ matrix.project }}
        # if: ${{ contains(steps.determine_changes.outputs.changed_paths, matrix.project) }}
        run: |
          npm install
          npm run build
        working-directory: ./${{ matrix.project }}

      - name: Deploy ${{ matrix.project }} via FTP
        # if: ${{ contains(steps.determine_changes.outputs.changed_paths, matrix.project) }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./${{ matrix.project }}/dist/
          server-dir: ${{ matrix.project == 'landing' && '/' || '/dashboard/' }}
